import os

# Specify the directory containing the Python files
directory = 'leet_own'

# Get a list of all the Python files in the specified directory
files = [f for f in os.listdir(directory) if f.endswith('.py')]

# Open the main file for writing
with open('main.py', 'w') as main_file:
  # Write a header for the main file
  main_file.write('# This file was generated by combining multiple Python files\n')
  
  # Iterate over the list of file names
  for file_name in files:
    # Open the current file for reading
    with open(os.path.join(directory, file_name), 'r') as f:
      # Write a comment indicating the name of the current file to the main file
      main_file.write('\n# File: {}\n'.format(file_name))
      # Write the contents of the current file to the main file
      main_file.write(f.read())

print('Combined Python files in specified directory into main.py')
